Q1. Is there any difference in the data type of variables list_ and array_list? If there is, print the data types of both variables.

In [22]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'str'>
Data type of array_list: <U1


Q2. Print the data type of each element of both variables list_ and array_list.

In [23]:
for element in list_:
    print(f"Data type of element in list_: {type(element)}")

for element in array_list:
    print(f"Data type of element in array_list: {type(element)}")


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q3. Will there be any difference in the data type of the elements present in both variables list_ and array_list? If so, print the data types of each element present in both variables list_ and array_list.

In [24]:
array_list = np.array(object=list_, dtype=int)

for element in list_:
    print(f"Data type of element in list_: {type(element)}")

for element in array_list:
    print(f"Data type of element in array_list: {type(element)}")


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


Q4. Characteristics of variable num_array:

In [25]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Q5. Create a numpy array of a 3x3 matrix containing zeros only.

In [26]:
import numpy as np

zero_array = np.zeros((3, 3))
print("Zero array:")
print(zero_array)


Zero array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions.

In [27]:
import numpy as np

identity_matrix = np.eye(5)
print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
