In [ ]:

Part 1: Theoretical Questions
1. Different Data Structures in TensorFlow:

TensorFlow uses several data structures to represent and manipulate data:

Tensor: The fundamental data structure in TensorFlow, a multi-dimensional array of data with a specific data type (e.g., integers, floats). Examples include a 2D image represented as a 2D array of pixel intensities, a 1D vector holding stock prices, or a 3D volume of medical data.
Scalar: A 0-dimensional tensor, essentially a single number.
Variable: A mutable tensor that holds state in your TensorFlow program. Its value can be updated during training or computation.
Constant: An immutable tensor with a predetermined value that cannot be changed after creation.
Dataset: A collection of tensors used for feeding data into your TensorFlow model during training or inference.

In [ ]:
2. TensorFlow Constant vs. Variable:

Both represent data, but with crucial differences:

Mutability:

Constant: Immutable, its value cannot be changed after creation. Useful for defining fixed parameters like learning rates or initial weights.
Variable: Mutable, its value can be updated during training or computation using operations like tf.assign. Used to store state and trainable parameters like model weights.
Initialization:

Constant: Initialized with a fixed value provided during creation.
Variable: Requires an initial value, but that value can be the result of computations or other operations.
Example:

Imagine a learning rate for an optimizer. You might define it as a constant like learning_rate = tf.constant(0.01).
Conversely, your model weights are variables initialized with random values and later updated during training based on the data.

In [ ]:
3. Matrix Operations in TensorFlow:

TensorFlow provides multiple ways to perform matrix operations:

Basic operators:

Addition: tf.add(matrix_a, matrix_b)
Subtraction: tf.subtract(matrix_a, matrix_b)
Multiplication: tf.matmul(matrix_a, matrix_b)
Built-in functions:

Transpose: tf.transpose(matrix)
Determinant: tf.linalg.det(matrix)
Eigenvalues: tf.linalg.eigvalsh(matrix)
Element-wise operations:

Apply element-wise addition, subtraction, multiplication, division, etc., using operators like +, -, *, / directly on tensors.
These examples cover basic operations. Many other advanced functionalities are available for more complex manipulations and numerical computations.

Remember, TensorFlow functions often operate on entire tensors at once, providing efficient manipulation of large datasets.


Part 2: Practical Implementation

Task 1: Creating and Manipulating Matrices

In [ ]:

Here's the Python code for the tasks you described, along with the expected output:

In [12]:
import tensorflow as tf

# Task 1: Create a normal matrix A (3x3)
matrix_A = tf.random.normal(shape=(3, 3))
print("Matrix A:")
print(matrix_A.numpy())

# Task 2: Create a Gaussian matrix B (3x3) to match the dimensions of A
matrix_B = tf.random.truncated_normal(shape=(3, 3))
print("\nMatrix B:")
print(matrix_B.numpy())

# Task 3: Create a matrix C with a custom normal distribution (3x3) to match the dimensions of A and B
mean, stddev = 3, 0.5
matrix_C = tf.random.normal(shape=(3, 3), mean=mean, stddev=stddev)
print("\nMatrix C:")
print(matrix_C.numpy())

# Task 4: Perform matrix addition between A and B, store the result in D
matrix_D = tf.add(matrix_A, matrix_B)
print("\nMatrix D (Result of A + B):")
print(matrix_D.numpy())

# Task 5: Perform matrix multiplication between C and D, store the result in E
matrix_E = tf.matmul(matrix_C, matrix_D)
print("\nMatrix E (Result of C * D):")
print(matrix_E.numpy())


Matrix A:
[[-0.5220494   0.14369836  0.9382226 ]
 [-0.32614037 -0.997453    0.8343614 ]
 [-0.31411338 -0.99141574  0.8817882 ]]

Matrix B:
[[-0.5582123  -0.12484179 -0.59601647]
 [-1.2169625   0.13567191 -1.5834138 ]
 [-0.19576868  1.5732236   0.3344054 ]]

Matrix C:
[[3.002276  2.9642513 2.9503138]
 [2.6925807 2.4984658 2.8446302]
 [3.031564  3.5107987 2.9492993]]

Matrix D (Result of A + B):
[[-1.0802617   0.01885657  0.34220612]
 [-1.5431029  -0.86178106 -0.74905246]
 [-0.5098821   0.58180785  1.2161936 ]]

Matrix E (Result of C * D):
[[ -9.321701   -0.7814072   2.39517  ]
 [ -8.214507   -0.4473294   2.5095568]
 [-10.1962     -1.2524495   1.9945662]]


Task 2: Performing Additional Matrix Operations

In [8]:
# Task 2.1: Create a matrix F with dimensions 3x3 using random_uniform
matrix_F = tf.random.uniform(shape=(3, 3))
print("\nMatrix F:")
print(matrix_F.numpy())

# Task 2.2: Calculate the transpose of matrix F and store the result in matrix G
matrix_G = tf.transpose(matrix_F)
print("\nMatrix G (Transpose of F):")
print(matrix_G.numpy())

# Task 2.3: Calculate the element-wise exponential of matrix F and store the result in matrix H
matrix_H = tf.exp(matrix_F)
print("\nMatrix H (Element-wise Exponential of F):")
print(matrix_H.numpy())

# Task 2.4: Create a matrix I by concatenating matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("\nMatrix I (Concatenation of F and G horizontally):")
print(matrix_I.numpy())

# Task 2.5: Create a matrix J by concatenating matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("\nMatrix J (Concatenation of F and H vertically):")
print(matrix_J.numpy())



Matrix F:
[[0.96595335 0.700438   0.21754801]
 [0.06525898 0.21781468 0.20961499]
 [0.7212229  0.5042896  0.73570514]]

Matrix G (Transpose of F):
[[0.96595335 0.06525898 0.7212229 ]
 [0.700438   0.21781468 0.5042896 ]
 [0.21754801 0.20961499 0.73570514]]

Matrix H (Element-wise Exponential of F):
[[2.6272912 2.0146348 1.2430251]
 [1.0674354 1.2433566 1.2332032]
 [2.056947  1.6558088 2.0869532]]

Matrix I (Concatenation of F and G horizontally):
[[0.96595335 0.700438   0.21754801 0.96595335 0.06525898 0.7212229 ]
 [0.06525898 0.21781468 0.20961499 0.700438   0.21781468 0.5042896 ]
 [0.7212229  0.5042896  0.73570514 0.21754801 0.20961499 0.73570514]]

Matrix J (Concatenation of F and H vertically):
[[0.96595335 0.700438   0.21754801]
 [0.06525898 0.21781468 0.20961499]
 [0.7212229  0.5042896  0.73570514]
 [2.6272912  2.0146348  1.2430251 ]
 [1.0674354  1.2433566  1.2332032 ]
 [2.056947   1.6558088  2.0869532 ]]
